spring:
  freemarker:
    template-loader-path: classpath:/web/views, claaspath:src/main/resources/web/views/
    cache: false
    settings:
      template_update_delay: 0
      number_format: 0.##
      apiBuiltinEnabled: true
      urlEscapingCharset: UTF-8
      templateExceptionHandler: htmlDebug
      incompatible_improvements: 2.3.26
  resources:
    static-locations: classpath:/vpaas/static/
  mvc:
    static-path-pattern: /vpas/static/**

server:
  port: 9020

management:
  server:
    port:
      9021
    ssl:
      enabled: false
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
    mappings:
      enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"

endpoints:
  alimetrics:
    enabled: true